name: Deploy

env:
  CARGO_TERM_COLOR: always

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        # Because it can be kicked off manually there may not be a tag
        continue-on-error: true

      - name: Set build suffix
        run: |
          echo "SUFFIX=$([[ "${{ steps.tag.outputs.tag }}" = "" ]] && echo $GITHUB_SHA || echo ${{ steps.tag.outputs.tag }})" >> $GITHUB_ENV
          DATE=$(date +'%Y-%m-%d_%H%M%S')
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "TAG=$([[ "${{ steps.tag.outputs.tag }}" = "" ]] && echo "main_$DATE" || echo "${{ steps.tag.outputs.tag }}")" >> $GITHUB_ENV
      
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build 📦
        run: |
          docker build -t app -f ./Dockerfile .

      - name: Build and push with `latest` tag
        run: |
          RUST_IMAGE_TAG=latest
          CHEF_PACKAGE_VERSION=latest
          CHEF_IMAGE=$DOCKER_REPO:$CHEF_PACKAGE_VERSION-rust-$RUST_IMAGE_TAG
          CHEF_IMAGE_LATEST=$DOCKER_REPO:latest-rust-$RUST_IMAGE_TAG

            # --tag $CHEF_IMAGE \
            # --tag $CHEF_IMAGE_LATEST \
            # --tag $DOCKER_REPO:latest \
            # --push \
            # --build-arg=BASE_IMAGE=rust:latest \
            # --build-arg=CHEF_TAG=$CHEF_PACKAGE_VERSION \
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t app \
            -f ./Dockerfile .

      - name: Prepare output
        run: |
          tree > output.lst
          tar --zstd -cvf artifacts-${{ env.SUFFIX }}.tar.zst output.lst

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.tar.*"
          tag: ${{ env.TAG }}
          overwrite: true
          file_glob: true
          prerelease: true

      - name: Release release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "README.md"
          tag: ${{ env.TAG }}
          overwrite: true
          promote: true
          prerelease: false